"use client";
import Link from "next/link";
import {useEffect,useRef,useState} from "react";
import {Plus,Upload} from "lucide-react";
import {apiGet,apiSend,type Job,type JobPage} from "@/lib/api";

const empty={company:"",role:"",location:"",job_url:"",description:"",deadline:"",job_type:"",industry:"",salary:"",application_start_date:"",campus_category:"",referral_available:"",graduation_cohort:"",company_type:""};

export function JobsClient({locale,copy}:{locale:string;copy:Record<string,string>}){
 const [jobs,setJobs]=useState<Job[]>([]),[keyword,setKeyword]=useState(""),[error,setError]=useState<string|null>(null),[matching,setMatching]=useState<string|null>(null),[loading,setLoading]=useState(true);
 const [adding,setAdding]=useState(false),[form,setForm]=useState(empty),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(20),[total,setTotal]=useState(0),[totalPages,setTotalPages]=useState(0),[refresh,setRefresh]=useState(0);
 const requestSequence=useRef(0);
 useEffect(()=>{const sequence=++requestSequence.current;setLoading(true);const timer=window.setTimeout(async()=>{try{const params=new URLSearchParams({page:String(page),page_size:String(pageSize)});if(keyword.trim())params.set("q",keyword.trim());const result=await apiGet<JobPage>(`/api/v1/jobs?${params}`);if(sequence===requestSequence.current){setJobs(result.items);setTotal(result.total);setTotalPages(result.total_pages);setError(null)}}catch(e){if(sequence===requestSequence.current)setError((e as Error).message)}finally{if(sequence===requestSequence.current)setLoading(false)}},300);return()=>window.clearTimeout(timer)},[keyword,page,pageSize,refresh]);
 async function create(){try{await apiSend("/api/v1/jobs","POST",{...form,role:form.role.trim()||null,referral_available:form.referral_available===""?null:form.referral_available==="true"});setForm(empty);setAdding(false);setPage(1);setRefresh(value=>value+1)}catch(e){setError((e as Error).message)}}
 return <div className="page-stack"><div className="flex flex-wrap items-end justify-between gap-5"><div><h1 className="page-heading">{copy.title}</h1><p className="page-subtitle">{copy.subtitle}</p></div><div className="flex gap-3"><button onClick={()=>setAdding(!adding)} className="btn-secondary"><Plus className="mr-2 inline h-4 w-4"/>{copy.add}</button><Link href={`/${locale}/jobs/import`} className="btn-primary"><Upload className="mr-2 inline h-4 w-4"/>{copy.import}</Link></div></div>
 {adding&&<section className="surface-card p-6"><div className="grid gap-4 md:grid-cols-2">{Object.keys(empty).map(k=><label key={k} className={k==="description"?"md:col-span-2":""}><span className="mb-1.5 block text-sm font-medium text-muted">{copy[k]||k}</span>{k==="description"?<textarea className="w-full rounded-md border p-3" value={form[k as keyof typeof form]} onChange={e=>setForm({...form,[k]:e.target.value})}/>:k==="referral_available"?<select className="h-10 w-full rounded-md border px-3" value={form.referral_available} onChange={e=>setForm({...form,referral_available:e.target.value})}><option value="">{copy.unknown}</option><option value="true">{copy.yes}</option><option value="false">{copy.no}</option></select>:<input type={k==="deadline"||k==="application_start_date"?"date":"text"} className="h-10 w-full rounded-md border px-3" value={form[k as keyof typeof form]} onChange={e=>setForm({...form,[k]:e.target.value})}/>}</label>)}</div><button disabled={!form.company.trim()} onClick={create} className="btn-primary mt-5">{copy.save}</button></section>}
 <div className="flex gap-3"><input value={keyword} onChange={e=>{setKeyword(e.target.value);setPage(1)}} placeholder={copy.keyword} className="h-10 w-full rounded-md border border-line px-3"/><select value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1)}} className="h-10 rounded-md border border-line px-3"><option value={20}>20</option><option value={50}>50</option></select></div>{error&&<p className="text-red-700">{error}</p>}
 <section className="space-y-4">{loading&&<div className="surface-card p-10 text-center text-muted">{copy.loading}</div>}{!loading&&jobs.length===0&&<div className="surface-card p-10 text-center text-muted">{keyword.trim()?copy.noMatches:copy.empty}</div>}{!loading&&jobs.map(job=><article key={job.id} className="surface-card p-6 hover:-translate-y-0.5 hover:border-brand/40 hover:shadow-md"><Link href={`/${locale}/jobs/${job.id}`}><h2 className="text-xl font-semibold tracking-[-0.02em]">{job.company}</h2><p className="mt-1.5 text-muted">{job.role||copy.roleMissing}</p><p className="mt-4 text-sm leading-6 text-muted">{[job.location,job.job_type,job.campus_category,job.graduation_cohort,job.deadline].filter(Boolean).join(" · ")||copy.metaMissing}</p></Link><div className="mt-5 border-t border-line pt-4"><MatchSummary match={job.match} copy={copy}/>{job.match?.status==="ready"&&<button disabled={matching===job.id} onClick={async()=>{try{setMatching(job.id);const match=await apiSend<Job["match"]>(`/api/v1/jobs/${job.id}/discovery-match`,"POST");setJobs(current=>current.map(item=>item.id===job.id?{...item,match}:item))}catch(e){setError((e as Error).message)}finally{setMatching(null)}}} className="btn-primary mt-3">{matching===job.id?copy.matching:copy.checkMatch}</button>}</div></article>)}</section>
 {!loading&&total>0&&<div className="flex items-center justify-between gap-3"><span className="text-sm text-muted">{copy.total.replace("{count}",String(total))}</span><div className="flex items-center gap-3"><button disabled={page<=1} onClick={()=>setPage(value=>value-1)} className="rounded border px-3 py-2 text-sm disabled:opacity-40">{copy.previous}</button><span className="text-sm">{copy.pageOf.replace("{page}",String(page)).replace("{totalPages}",String(totalPages))}</span><button disabled={page>=totalPages} onClick={()=>setPage(value=>value+1)} className="rounded border px-3 py-2 text-sm disabled:opacity-40">{copy.next}</button></div></div>}
 </div>
}

function MatchSummary({match,copy}:{match:Job["match"];copy:Record<string,string>}){if(!match)return null;if(match.status==="scored")return <div><strong>{match.overall_score}% {copy.match}</strong><p className="mt-1 text-sm text-muted">{match.matched_skills.slice(0,3).join(" · ")||copy.noSkillSignals}</p></div>;if(match.status==="semantic_only")return <div><strong>{copy.potentialMatch}</strong><p className="mt-1 text-sm text-muted">{copy.semanticRelevance}: {match.semantic_score}% · {copy.limitedSignals}</p></div>;if(match.status==="limited_data")return <div><strong>{copy.limitedData}</strong><p className="mt-1 text-sm text-muted">{copy.limitedExplanation}</p></div>;if(match.status==="no_resume")return <p className="text-sm text-muted">{copy.resumeNeeded}</p>;return <p className="text-sm text-muted">{copy.readyToMatch}</p>}
